### ISSUE TITLE
使用NapCatQQ发送转发合并消息失败

### ISSUE THREAD

**Issue by Kayaneru** [TimeRainStarSky/Yunzai#107]
环境：Ubuntu 22.04 LTS，TRSS云崽最新版，LinuxNTQQ3.2.9-24568，NapCatQQ1.5.8
（网上搜了下没搜到同样的情况，不知道是我哪里部署的有问题）
单条消息能正常发送，所有的转发合并消息发送失败，日志如下：
<pre class="notranslate"><code class="notranslate">
0|TRSS-Yunzai  | [16:40:12.832][INFO][1342664055 <= 127589547, 377708175] 群消息：[orz, 你] 锅巴登陆
0|TRSS-Yunzai  | [16:40:12.856][INFO][127589547, 你(377708175)][锅巴登陆][锅巴登录(login)][开始处理]
0|TRSS-Yunzai  | [16:40:12.866][INFO][1342664055 => 127589547] 发送群转发消息：[{"user_id":1342664055,"nickname":"orz","message":"欢迎回来主人~\n这是您的登录地址："},{"user_id":1342664055,"nickname":"orz","message":"内网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836"},{"user_id":1342664055,"nickname":"orz","message":"外网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836"},{"user_id":1342664055,"nickname":"orz","message":"临时令牌3分钟内有效（请勿轻易告知他人哦），使用过后会立即失效，若登录成功将会在使用者的浏览器上生成个24小时内有效的令牌，过期后需要重新登录~"}]
0|TRSS-Yunzai  | [16:40:12.921][INFO][1342664055 <= 1342664055] 好友消息：[orz] 欢迎回来主人~
0|TRSS-Yunzai  | 这是您的登录地址：
0|TRSS-Yunzai  | [16:40:17.917][INFO][1342664055 <= 1342664055] 好友消息：[orz] 内网地址：
0|TRSS-Yunzai  | http://xxxx:2536/guoba/#/ml/40j836
0|TRSS-Yunzai  | [16:40:22.919][INFO][1342664055 <= 1342664055] 好友消息：[orz] 外网地址：
0|TRSS-Yunzai  | http://xxxx:2536/guoba/#/ml/40j836
0|TRSS-Yunzai  | [16:40:27.923][INFO][1342664055 <= 1342664055] 好友消息：[orz] 临时令牌3分钟内有效（请勿轻易告知他人哦），使用过后会立即失效，若登录成功将会在使用者的浏览器上生成个24小时内有效的令牌，过期后需要重新登录~
0|TRSS-Yunzai  | [16:40:32.883][ERRO][1342664055] 发送消息错误 {
0|TRSS-Yunzai  |   type: 'node',
0|TRSS-Yunzai  |   data: [
0|TRSS-Yunzai  |     { user_id: 1342664055, nickname: 'orz', message: '欢迎回来主人~\n这是您的登录地址：' },
0|TRSS-Yunzai  |     {
0|TRSS-Yunzai  |       user_id: 1342664055,
0|TRSS-Yunzai  |       nickname: 'orz',
0|TRSS-Yunzai  |       message: '内网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836'
0|TRSS-Yunzai  |     },
0|TRSS-Yunzai  |     {
0|TRSS-Yunzai  |       user_id: 1342664055,
0|TRSS-Yunzai  |       nickname: 'orz',
0|TRSS-Yunzai  |       message: '外网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836'
0|TRSS-Yunzai  |     },
0|TRSS-Yunzai  |     {
0|TRSS-Yunzai  |       user_id: 1342664055,
0|TRSS-Yunzai  |       nickname: 'orz',
0|TRSS-Yunzai  |       message: '临时令牌3分钟内有效（请勿轻易告知他人哦），使用过后会立即失效，若登录成功将会在使用者的浏览器上生成个24小时内有效的令牌，过期后需要重新登录~'
0|TRSS-Yunzai  |     },
0|TRSS-Yunzai  |     [length]: 4
0|TRSS-Yunzai  |   ]
0|TRSS-Yunzai  | } {
0|TRSS-Yunzai  |   action: 'send_group_forward_msg',
0|TRSS-Yunzai  |   params: {
0|TRSS-Yunzai  |     group_id: 127589547,
0|TRSS-Yunzai  |     messages: [
0|TRSS-Yunzai  |       {
0|TRSS-Yunzai  |         type: 'node',
0|TRSS-Yunzai  |         data: {
0|TRSS-Yunzai  |           name: 'orz',
0|TRSS-Yunzai  |           uin: '1342664055',
0|TRSS-Yunzai  |           content: [ { type: 'text', data: { text: '欢迎回来主人~\n这是您的登录地址：' } }, [length]: 1 ],
0|TRSS-Yunzai  |           time: undefined
0|TRSS-Yunzai  |         }
0|TRSS-Yunzai  |       },
0|TRSS-Yunzai  |       {
0|TRSS-Yunzai  |         type: 'node',
0|TRSS-Yunzai  |         data: {
0|TRSS-Yunzai  |           name: 'orz',
0|TRSS-Yunzai  |           uin: '1342664055',
0|TRSS-Yunzai  |           content: [
0|TRSS-Yunzai  |             {
0|TRSS-Yunzai  |               type: 'text',
0|TRSS-Yunzai  |               data: { text: '内网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836' }
0|TRSS-Yunzai  |             },
0|TRSS-Yunzai  |             [length]: 1
0|TRSS-Yunzai  |           ],
0|TRSS-Yunzai  |           time: undefined
0|TRSS-Yunzai  |         }
0|TRSS-Yunzai  |       },
0|TRSS-Yunzai  |       {
0|TRSS-Yunzai  |         type: 'node',
0|TRSS-Yunzai  |         data: {
0|TRSS-Yunzai  |           name: 'orz',
0|TRSS-Yunzai  |           uin: '1342664055',
0|TRSS-Yunzai  |           content: [
0|TRSS-Yunzai  |             {
0|TRSS-Yunzai  |               type: 'text',
0|TRSS-Yunzai  |               data: { text: '外网地址：\nhttp://xxxx:2536/guoba/#/ml/40j836' }
0|TRSS-Yunzai  |             },
0|TRSS-Yunzai  |             [length]: 1
0|TRSS-Yunzai  |           ],
0|TRSS-Yunzai  |           time: undefined
0|TRSS-Yunzai  |         }
0|TRSS-Yunzai  |       },
0|TRSS-Yunzai  |       {
0|TRSS-Yunzai  |         type: 'node',
0|TRSS-Yunzai  |         data: {
0|TRSS-Yunzai  |           name: 'orz',
0|TRSS-Yunzai  |           uin: '1342664055',
0|TRSS-Yunzai  |           content: [
0|TRSS-Yunzai  |             {
0|TRSS-Yunzai  |               type: 'text',
0|TRSS-Yunzai  |               data: {
0|TRSS-Yunzai  |                 text: '临时令牌3分钟内有效（请勿轻易告知他人哦），使用过后会立即失效，若登录成功将会在使用者的浏览器上生成个24小时内有效的令牌，过期后需要重新登录~'
0|TRSS-Yunzai  |               }
0|TRSS-Yunzai  |             },
0|TRSS-Yunzai  |             [length]: 1
0|TRSS-Yunzai  |           ],
0|TRSS-Yunzai  |           time: undefined
0|TRSS-Yunzai  |         }
0|TRSS-Yunzai  |       },
0|TRSS-Yunzai  |       [length]: 4
0|TRSS-Yunzai  |     ]
0|TRSS-Yunzai  |   },
0|TRSS-Yunzai  |   echo: '01J0TCVBA35K8NCFN6ZYCRYD72',
0|TRSS-Yunzai  |   error: {
0|TRSS-Yunzai  |     status: 'failed',
0|TRSS-Yunzai  |     retcode: 1200,
0|TRSS-Yunzai  |     data: null,
0|TRSS-Yunzai  |     message: 'Error: 转发消息失败，生成节点为空\n' +
0|TRSS-Yunzai  |       '    at handleForwardNode (file:///root/NapCat/napcat.mjs:26229:11)\n' +
0|TRSS-Yunzai  |       '    at runNextTicks (node:internal/process/task_queues:60:5)\n' +
0|TRSS-Yunzai  |       '    at listOnTimeout (node:internal/timers:538:9)\n' +
0|TRSS-Yunzai  |       '    at process.processTimers (node:internal/timers:512:7)\n' +
0|TRSS-Yunzai  |       '    at async GoCQHTTPSendGroupForwardMsg._handle (file:///root/NapCat/napcat.mjs:26366:26)\n' +
0|TRSS-Yunzai  |       '    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///root/NapCat/napcat.mjs:25818:23)\n' +
0|TRSS-Yunzai  |       '    at async ReverseWebsocket.onmessage (file:///root/NapCat/napcat.mjs:30731:28)\n' +
0|TRSS-Yunzai  |       '    at async WebSocket.<anonymous> (file:///root/NapCat/napcat.mjs:30770:7)',
0|TRSS-Yunzai  |     wording: 'Error: 转发消息失败，生成节点为空\n' +
0|TRSS-Yunzai  |       '    at handleForwardNode (file:///root/NapCat/napcat.mjs:26229:11)\n' +
0|TRSS-Yunzai  |       '    at runNextTicks (node:internal/process/task_queues:60:5)\n' +
0|TRSS-Yunzai  |       '    at listOnTimeout (node:internal/timers:538:9)\n' +
0|TRSS-Yunzai  |       '    at process.processTimers (node:internal/timers:512:7)\n' +
0|TRSS-Yunzai  |       '    at async GoCQHTTPSendGroupForwardMsg._handle (file:///root/NapCat/napcat.mjs:26366:26)\n' +
0|TRSS-Yunzai  |       '    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///root/NapCat/napcat.mjs:25818:23)\n' +
0|TRSS-Yunzai  |       '    at async ReverseWebsocket.onmessage (file:///root/NapCat/napcat.mjs:30731:28)\n' +
0|TRSS-Yunzai  |       '    at async WebSocket.<anonymous> (file:///root/NapCat/napcat.mjs:30770:7)',
0|TRSS-Yunzai  |     echo: '01J0TCVBA35K8NCFN6ZYCRYD72',
0|TRSS-Yunzai  |     raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 转发消息失败，生成节点为空\\n    at handleForwardNode (file:///root/NapCat/napcat.mjs:26229:11)\\n    at runNextTicks (node:internal/process/task_queues:60:5)\\n    at listOnTimeout (node:internal/timers:538:9)\\n    at process.processTimers (node:internal/timers:512:7)\\n    at async GoCQHTTPSendGroupForwardMsg._handle (file:///root/NapCat/napcat.mjs:26366:26)\\n    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///root/NapCat/napcat.mjs:25818:23)\\n    at async ReverseWebsocket.onmessage (file:///root/NapCat/napcat.mjs:30731:28)\\n    at async WebSocket.<anonymous> (file:///root/NapCat/napcat.mjs:30770:7)","wording":"Error: 转发消息失败，生成节点为空\\n    at handleForwardNode (file:///root/NapCat/napcat.mjs:26229:11)\\n    at runNextTicks (node:internal/process/task_queues:60:5)\\n    at listOnTimeout (node:internal/timers:538:9)\\n    at process.processTimers (node:internal/timers:512:7)\\n    at async GoCQHTTPSendGroupForwardMsg._handle (file:/'... 332 more characters
0|TRSS-Yunzai  |   }
0|TRSS-Yunzai  | }
0|TRSS-Yunzai  | [16:40:32.885][MARK][127589547, 你(377708175)][锅巴登陆][锅巴登录(login)][完成20.029秒]
</code></pre>

**Comment by Kayaneru** [comment]
问题已解决，机器人qq需要添加自己为好友
