### ISSUE TITLE
接入LLOneBot后发图异常

### ISSUE THREAD

**Issue by QAQQL** [TimeRainStarSky/Yunzai#120]
## 问题
  `#帮助`  没有返回,后台log显示如下
![图片](https://github.com/user-attachments/assets/f48ae2cf-bb86-40e3-b0ea-43ec047df32d)

OneBotv11(QQ) LLOneBot v3.28.0
LLOneBot配置如下
![图片](https://github.com/user-attachments/assets/8fb4db99-0f39-4616-b116-8c8efec8f487)

13579为另一款bot,发送图片没有问题

## 环境
自建docker镜像,编译自项目 [TRSS-Yunzai-Bot-Docker](https://github.com/QAQQL/TRSS-Yunzai-Bot-Docker)

## 报错代码

```bash

2024-08-07 21:14:08 [21:14:08.054][ERRO][unhandledRejection] Error
2024-08-07 21:14:08     at OneBotv11Adapter.sendApi (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:21:19)
2024-08-07 21:14:08     at Object.sendApi (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:709:41)
2024-08-07 21:14:08     at file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:103:16
2024-08-07 21:14:08     at OneBotv11Adapter.sendMsg (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:91:22)
2024-08-07 21:14:08     at async e.reply (file:///app/TRSS-Yunzai/lib/plugins/loader.js:480:15)
2024-08-07 21:14:08     at async Runtime.render (file:///app/TRSS-Yunzai/lib/plugins/runtime.js:230:15)
2024-08-07 21:14:08     at async cls.render (file:///app/TRSS-Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)
2024-08-07 21:14:08     at async cls.<computed> [as help] (file:///app/TRSS-Yunzai/plugins/miao-plugin/components/App.js:96:18)
2024-08-07 21:14:08     at async PluginsLoader.deal (file:///app/TRSS-Yunzai/lib/plugins/loader.js:264:41) {
2024-08-07 21:14:08   [stack]: 'Error\n' +
2024-08-07 21:14:08     '    at OneBotv11Adapter.sendApi (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
2024-08-07 21:14:08     '    at Object.sendApi (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:709:41)\n' +
2024-08-07 21:14:08     '    at file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:103:16\n' +
2024-08-07 21:14:08     '    at OneBotv11Adapter.sendMsg (file:///app/TRSS-Yunzai/plugins/adapter/OneBotv11.js:91:22)\n' +
2024-08-07 21:14:08     '    at async e.reply (file:///app/TRSS-Yunzai/lib/plugins/loader.js:480:15)\n' +
2024-08-07 21:14:08     '    at async Runtime.render (file:///app/TRSS-Yunzai/lib/plugins/runtime.js:230:15)\n' +
2024-08-07 21:14:08     '    at async cls.render (file:///app/TRSS-Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)\n' +
2024-08-07 21:14:08     '    at async cls.<computed> [as help] (file:///app/TRSS-Yunzai/plugins/miao-plugin/components/App.js:96:18)\n' +
2024-08-07 21:14:08     '    at async PluginsLoader.deal (file:///app/TRSS-Yunzai/lib/plugins/loader.js:264:41)',
2024-08-07 21:14:08   action: 'send_msg',
2024-08-07 21:14:08   params: {
2024-08-07 21:14:08     user_id: xxxxxxx,
2024-08-07 21:14:08     message: [
2024-08-07 21:14:08       {
2024-08-07 21:14:08         type: 'image',
2024-08-07 21:14:08         data: {
2024-08-07 21:14:08           type: undefined,
2024-08-07 21:14:08           file: '{"0":255,"1":216,"2":255,"3":224,"4":0,"5":16,"6":74,"7":70,"8":73,"9":70,"10":0,"11":1,"12":1,"13":0,"14":0,"15":1,"16":0,"17":1,"18":0,"19":0,"20":255,"21":226,"22":1,"23":216,"24":73,"25":67,"26":67,"27":95,"28":80,"29":82,"30":79,"31":70,"32":73,"33":76,"34":69,"35":0,"36":1,"37":1,"38":0,"39":0,"40":1,"41":200,"42":0,"43":0,"44":0,"45":0,"46":4,"47":48,"48":0,"49":0,"50":109,"51":110,"52":116,"53":114,"54":82,"55":71,"56":66,"57":32,"58":88,"59":89,"60":90,"61":32,"62":7,"63":224,"64":0,"65":1,"66":0,"67":1,"68":0,"69":0,"70":0,"71":0,"72":0,"73":0,"74":97,"75":99,"76":115,"77":112,"78":0,"79":0,"80":0,"81":0,"82":0,"83":0,"84":0,"85":0,"86":0,"87":0,"88":0,"89":0,"90":0,"91":0,"92":0,"93":0,"94":0,"95":0,"96":0,"97":0,"98":0,"99":0,"100":0,"101":0,"102":0,"103":0,"104":0,"105":1,"106":0,"107":0,"108":246,"109":214,"110":0,"111":1,"112":0,"113":0,"114":0,"115":0,"116":211,"117":45,"118":0,"119":0,"120":0,"121":0,"122":0,"123":0,"124":0,"125":0,"126":0,"127":0,"128":0,"129":0,"130"'... 4105880 more characters,
2024-08-07 21:14:08           name: undefined
2024-08-07 21:14:08         }
2024-08-07 21:14:08       },
2024-08-07 21:14:08       [length]: 1
2024-08-07 21:14:08     ]
2024-08-07 21:14:08   },
2024-08-07 21:14:08   echo: '01J4PFKCA3XSHTWZY7FVEJDYEB',
2024-08-07 21:14:08   error: {
2024-08-07 21:14:08     status: 'failed',
2024-08-07 21:14:08     retcode: 1200,
2024-08-07 21:14:08     data: null,
2024-08-07 21:14:08     message: 'uri {"0":255,"1":216,"2":255,"3":224,"4":0,"5":16,"6":74,"7":70,"8":73,"9":70,"10":0,"11":1,"12":1,"13":0,"14":0,"15":1,"16":0,"17":1,"18":0,"19":0,"20":255,"21":226,"22":1,"23":216,"24":73,"25":67,"26":67,"27":95,"28":80,"29":82,"30":79,"31":70,"32":73,"33":76,"34":69,"35":0,"36":1,"37":1,"38":0,"39":0,"40":1,"41":200,"42":0,"43":0,"44":0,"45":0,"46":4,"47":48,"48":0,"49":0,"50":109,"51":110,"52":116,"53":114,"54":82,"55":71,"56":66,"57":32,"58":88,"59":89,"60":90,"61":32,"62":7,"63":224,"64":0,"65":1,"66":0,"67":1,"68":0,"69":0,"70":0,"71":0,"72":0,"73":0,"74":97,"75":99,"76":115,"77":112,"78":0,"79":0,"80":0,"81":0,"82":0,"83":0,"84":0,"85":0,"86":0,"87":0,"88":0,"89":0,"90":0,"91":0,"92":0,"93":0,"94":0,"95":0,"96":0,"97":0,"98":0,"99":0,"100":0,"101":0,"102":0,"103":0,"104":0,"105":1,"106":0,"107":0,"108":246,"109":214,"110":0,"111":1,"112":0,"113":0,"114":0,"115":0,"116":211,"117":45,"118":0,"119":0,"120":0,"121":0,"122":0,"123":0,"124":0,"125":0,"126":0,"127":0,"128":0,"129":0,"'... 8212798 more characters,
2024-08-07 21:14:08     wording: 'uri {"0":255,"1":216,"2":255,"3":224,"4":0,"5":16,"6":74,"7":70,"8":73,"9":70,"10":0,"11":1,"12":1,"13":0,"14":0,"15":1,"16":0,"17":1,"18":0,"19":0,"20":255,"21":226,"22":1,"23":216,"24":73,"25":67,"26":67,"27":95,"28":80,"29":82,"30":79,"31":70,"32":73,"33":76,"34":69,"35":0,"36":1,"37":1,"38":0,"39":0,"40":1,"41":200,"42":0,"43":0,"44":0,"45":0,"46":4,"47":48,"48":0,"49":0,"50":109,"51":110,"52":116,"53":114,"54":82,"55":71,"56":66,"57":32,"58":88,"59":89,"60":90,"61":32,"62":7,"63":224,"64":0,"65":1,"66":0,"67":1,"68":0,"69":0,"70":0,"71":0,"72":0,"73":0,"74":97,"75":99,"76":115,"77":112,"78":0,"79":0,"80":0,"81":0,"82":0,"83":0,"84":0,"85":0,"86":0,"87":0,"88":0,"89":0,"90":0,"91":0,"92":0,"93":0,"94":0,"95":0,"96":0,"97":0,"98":0,"99":0,"100":0,"101":0,"102":0,"103":0,"104":0,"105":1,"106":0,"107":0,"108":246,"109":214,"110":0,"111":1,"112":0,"113":0,"114":0,"115":0,"116":211,"117":45,"118":0,"119":0,"120":0,"121":0,"122":0,"123":0,"124":0,"125":0,"126":0,"127":0,"128":0,"129":0,"'... 8212798 more characters,
2024-08-07 21:14:08     echo: '01J4PFKCA3XSHTWZY7FVEJDYEB',
2024-08-07 21:14:08     raw: '{"status":"failed","retcode":1200,"data":null,"message":"uri {\\"0\\":255,\\"1\\":216,\\"2\\":255,\\"3\\":224,\\"4\\":0,\\"5\\":16,\\"6\\":74,\\"7\\":70,\\"8\\":73,\\"9\\":70,\\"10\\":0,\\"11\\":1,\\"12\\":1,\\"13\\":0,\\"14\\":0,\\"15\\":1,\\"16\\":0,\\"17\\":1,\\"18\\":0,\\"19\\":0,\\"20\\":255,\\"21\\":226,\\"22\\":1,\\"23\\":216,\\"24\\":73,\\"25\\":67,\\"26\\":67,\\"27\\":95,\\"28\\":80,\\"29\\":82,\\"30\\":79,\\"31\\":70,\\"32\\":73,\\"33\\":76,\\"34\\":69,\\"35\\":0,\\"36\\":1,\\"37\\":1,\\"38\\":0,\\"39\\":0,\\"40\\":1,\\"41\\":200,\\"42\\":0,\\"43\\":0,\\"44\\":0,\\"45\\":0,\\"46\\":4,\\"47\\":48,\\"48\\":0,\\"49\\":0,\\"50\\":109,\\"51\\":110,\\"52\\":116,\\"53\\":114,\\"54\\":82,\\"55\\":71,\\"56\\":66,\\"57\\":32,\\"58\\":88,\\"59\\":89,\\"60\\":90,\\"61\\":32,\\"62\\":7,\\"63\\":224,\\"64\\":0,\\"65\\":1,\\"66\\":0,\\"67\\":1,\\"68\\":0,\\"69\\":0,\\"70\\":0,\\"71\\":0,\\"72\\":0,\\"73\\":0,\\"74\\":97,\\"75\\":99,\\"76\\":115,\\"77\\":112,\\"78\\":0,\\"79\\":0,\\"80\\":0,\\"81\\":0,\\"82\\":0,\\"83\\":0,\\"84\\":0,\\"85\\":0,\\"86\\":0,\\"87\\":0,\\"88\\":0,\\"89\\":0,\\"90\\":0,\\"91\\":0,\\"92\\":0,\\"93\\":0,\\"94\\":0,\\"95\\":0,\\"96\\":0,\\"97\\":0,\\"98\\":0,'... 19110760 more characters
2024-08-07 21:14:08   }
2024-08-07 21:14:08 }

```

**Comment by Dreamry2C** [comment]
同，应该是一样的问题。文字bot能发，但是图片这些发不了。
![image](https://github.com/user-attachments/assets/39c6dedb-4772-4ed7-b6db-9fbda724b43f)
![image](https://github.com/user-attachments/assets/397a7425-2182-473b-bd95-78cb54c51bd5)
![image](https://github.com/user-attachments/assets/6c8a801e-ff8b-42a5-bfca-a1e07b7282ff)
下面是，Lagrange.Core的显示
好像是说链接太长了
![image](https://github.com/user-attachments/assets/a9bfa183-1a2a-4078-946b-b8aa98e9b395)

**Comment by TimeRainStarSky** [comment]
已修复

**Comment by QAQQL** [comment]
实测已修复,感谢
