### ISSUE TITLE
NapCat 2.0.11使用反向WS对接，后台日志持续显示请求超时

### ISSUE THREAD

**Issue by Starfallan** [TimeRainStarSky/Yunzai#123]
更新2.0.11版本后可正常使用，但是后台持续报错,以下报错信息循环显示，内容相同
![Clip_2024-08-13_17-50-42](https://github.com/user-attachments/assets/f142663e-f2a9-476f-983c-a93e609b7b73)

```javascript
0|TRSS-Yun | [17:48:07.410][ERRO][2128368772] 请求超时 {
0|TRSS-Yun |   action: '_set_model_show',
0|TRSS-Yun |   params: { model: 'TRSS Yunzai ', model_show: 'TRSS Yunzai ' },
0|TRSS-Yun |   echo: '01J55J4NRG2TYBFJZ458P6K34S'
0|TRSS-Yun | }
0|TRSS-Yun | [17:48:07.410][MARK][ws://localhost:2536/OneBotv11 <≠> ::1:51184-TDKkRZRR3Adj4sKMmWcGNg==] 断开连接
0|TRSS-Yun | [17:48:07.415][ERRO][2128368772] 请求超时 { action: 'get_guild_service_profile', params: {}, echo: '01J55J4NRP5VKYTDK9BRDPRHV1' }
0|TRSS-Yun | [17:48:07.416][ERRO][unhandledRejection] TypeError: Cannot read properties of undefined (reading 'data')
0|TRSS-Yun |     at OneBotv11Adapter.connect (file:///usr/Miao-Yunzai/plugins/adapter/OneBotv11.js:763:101)
0|TRSS-Yun |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|TRSS-Yun |   [stack]: "TypeError: Cannot read properties of undefined (reading 'data')\n" +
0|TRSS-Yun |     '    at OneBotv11Adapter.connect (file:///usr/Miao-Yunzai/plugins/adapter/OneBotv11.js:763:101)\n' +
0|TRSS-Yun |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
0|TRSS-Yun |   [message]: "Cannot read properties of undefined (reading 'data')"
0|TRSS-Yun | }
0|TRSS-Yun | [17:48:12.414][MARK][ws://localhost:2536/OneBotv11 <=> ::1:51192-u/ALpib3TKSAsk/2WUzbWQ==] 建立连接 {
0|TRSS-Yun |   'x-self-id': '2128368772',
0|TRSS-Yun |   authorization: 'Bearer',
0|TRSS-Yun |   'x-client-role': 'Universal',
0|TRSS-Yun |   'user-agent': 'OneBot/11',
0|TRSS-Yun |   'sec-websocket-version': '13',
0|TRSS-Yun |   'sec-websocket-key': 'u/ALpib3TKSAsk/2WUzbWQ==',
0|TRSS-Yun |   connection: 'Upgrade',
0|TRSS-Yun |   upgrade: 'websocket',
0|TRSS-Yun |   'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
0|TRSS-Yun |   host: 'localhost:2536'
0|TRSS-Yun | }
0|TRSS-Yun | [17:48:12.415][WARN][TRSSYz] 未知消息：{}
0|TRSS-Yun | [17:48:12.416][WARN][TRSSYz] 未知消息：{}
```

**Comment by Starfallan** [comment]
补充，更新Napcat2.0.4后问题依旧

**Comment by TimeRainStarSky** [comment]
NapCat问题找NapCat作者
