### ISSUE TITLE
ob11 私聊图片发送失败

### ISSUE THREAD

**Issue by shoucandanghehe** [TimeRainStarSky/Yunzai#131]
使用协议端为napcat
```
0|TRSS-Yunzai  | [20:20:56.669][MARK][呵呵です🏳️‍🌈(1748609927)][#帮助][喵喵:喵喵帮助(help)][完成1.385秒]
0|TRSS-Yunzai  | Error
0|TRSS-Yunzai  |     at OneBotv11Adapter.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:21:19)
0|TRSS-Yunzai  |     at Object.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:709:41)
0|TRSS-Yunzai  |     at file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:103:16
0|TRSS-Yunzai  |     at OneBotv11Adapter.sendMsg (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:91:22)
0|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|TRSS-Yunzai  |     at async e.reply (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:444:15)
0|TRSS-Yunzai  |     at async Runtime.render (file:///home/scdhh/bot/Yunzai/lib/plugins/runtime.js:230:15)
0|TRSS-Yunzai  |     at async cls.render (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)
0|TRSS-Yunzai  |     at async cls.<computed> [as help] (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/components/App.js:96:18)
0|TRSS-Yunzai  |     at async PluginsLoader.deal (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:262:41) {
0|TRSS-Yunzai  |   action: 'send_msg',
0|TRSS-Yunzai  |   params: { user_id: 1748609927, message: [ [Object] ] },
0|TRSS-Yunzai  |   echo: '01J87P1MPMFP04ENZ3HTRE85SA',
0|TRSS-Yunzai  |   error: {
0|TRSS-Yunzai  |     status: 'failed',
0|TRSS-Yunzai  |     retcode: 1200,
0|TRSS-Yunzai  |     data: null,
0|TRSS-Yunzai  |     message: 'Error: 请指定 group_id 或 user_id\n' +
0|TRSS-Yunzai  |       '    at createContext (file:///app/napcat/napcat.mjs:36663:9)\n' +
0|TRSS-Yunzai  |       '    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\n' +
0|TRSS-Yunzai  |       '    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\n' +
0|TRSS-Yunzai  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
0|TRSS-Yunzai  |       '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)',
0|TRSS-Yunzai  |     wording: 'Error: 请指定 group_id 或 user_id\n' +
0|TRSS-Yunzai  |       '    at createContext (file:///app/napcat/napcat.mjs:36663:9)\n' +
0|TRSS-Yunzai  |       '    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\n' +
0|TRSS-Yunzai  |       '    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\n' +
0|TRSS-Yunzai  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
0|TRSS-Yunzai  |       '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)',
0|TRSS-Yunzai  |     echo: '01J87P1MPMFP04ENZ3HTRE85SA',
0|TRSS-Yunzai  |     raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 请指定 group_id 或 user_id\\n    at createContext (file:///app/napcat/napcat.mjs:36663:9)\\n    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\\n    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)","wording":"Error: 请指定 group_id 或 user_id\\n    at createContext (file:///app/napcat/napcat.mjs:36663:9)\\n    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\\n    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)","echo":"01J87P1MPMFP04ENZ3HTRE85SA"}'
0|TRSS-Yunzai  |   }
0|TRSS-Yunzai  | }
0|TRSS-Yunzai  | [20:20:56.688][ERRO][unhandledRejection] Error
0|TRSS-Yunzai  |     at OneBotv11Adapter.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:21:19)
0|TRSS-Yunzai  |     at Object.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:709:41)
0|TRSS-Yunzai  |     at file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:103:16
0|TRSS-Yunzai  |     at OneBotv11Adapter.sendMsg (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:91:22)
0|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|TRSS-Yunzai  |     at async e.reply (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:444:15)
0|TRSS-Yunzai  |     at async Runtime.render (file:///home/scdhh/bot/Yunzai/lib/plugins/runtime.js:230:15)
0|TRSS-Yunzai  |     at async cls.render (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)
0|TRSS-Yunzai  |     at async cls.<computed> [as help] (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/components/App.js:96:18)
0|TRSS-Yunzai  |     at async PluginsLoader.deal (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:262:41) {
0|TRSS-Yunzai  |   [stack]: 'Error\n' +
0|TRSS-Yunzai  |     '    at OneBotv11Adapter.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
0|TRSS-Yunzai  |     '    at Object.sendApi (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:709:41)\n' +
0|TRSS-Yunzai  |     '    at file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:103:16\n' +
0|TRSS-Yunzai  |     '    at OneBotv11Adapter.sendMsg (file:///home/scdhh/bot/Yunzai/plugins/adapter/OneBotv11.js:91:22)\n' +
0|TRSS-Yunzai  |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
0|TRSS-Yunzai  |     '    at async e.reply (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:444:15)\n' +
0|TRSS-Yunzai  |     '    at async Runtime.render (file:///home/scdhh/bot/Yunzai/lib/plugins/runtime.js:230:15)\n' +
0|TRSS-Yunzai  |     '    at async cls.render (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)\n' +
0|TRSS-Yunzai  |     '    at async cls.<computed> [as help] (file:///home/scdhh/bot/Yunzai/plugins/miao-plugin/components/App.js:96:18)\n' +
0|TRSS-Yunzai  |     '    at async PluginsLoader.deal (file:///home/scdhh/bot/Yunzai/lib/plugins/loader.js:262:41)',
0|TRSS-Yunzai  |   action: 'send_msg',
0|TRSS-Yunzai  |   params: {
0|TRSS-Yunzai  |     user_id: 1748609927,
0|TRSS-Yunzai  |     message: [
0|TRSS-Yunzai  |       {
0|TRSS-Yunzai  |         type: 'image',
0|TRSS-Yunzai  |         data: {
0|TRSS-Yunzai  |           type: undefined,
0|TRSS-Yunzai  |           file: 'base64:///9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAahA94DASIAAhEBAxEB/8QAHQAAAAcBAQEAAAAAAAAAAAAAAQIDBAUGBwgACf/EAGsQAAEDAwIDAwYICQMOCQoBDQECAwQABREGEgchMRNBUQgUImFx0RUyUlSBkZKTFiMzQlNylNLTQ0S'... 446413 more characters,
0|TRSS-Yunzai  |           name: undefined
0|TRSS-Yunzai  |         }
0|TRSS-Yunzai  |       },
0|TRSS-Yunzai  |       [length]: 1
0|TRSS-Yunzai  |     ]
0|TRSS-Yunzai  |   },
0|TRSS-Yunzai  |   echo: '01J87P1MPMFP04ENZ3HTRE85SA',
0|TRSS-Yunzai  |   error: {
0|TRSS-Yunzai  |     status: 'failed',
0|TRSS-Yunzai  |     retcode: 1200,
0|TRSS-Yunzai  |     data: null,
0|TRSS-Yunzai  |     message: 'Error: 请指定 group_id 或 user_id\n' +
0|TRSS-Yunzai  |       '    at createContext (file:///app/napcat/napcat.mjs:36663:9)\n' +
0|TRSS-Yunzai  |       '    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\n' +
0|TRSS-Yunzai  |       '    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\n' +
0|TRSS-Yunzai  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
0|TRSS-Yunzai  |       '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)',
0|TRSS-Yunzai  |     wording: 'Error: 请指定 group_id 或 user_id\n' +
0|TRSS-Yunzai  |       '    at createContext (file:///app/napcat/napcat.mjs:36663:9)\n' +
0|TRSS-Yunzai  |       '    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\n' +
0|TRSS-Yunzai  |       '    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\n' +
0|TRSS-Yunzai  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
0|TRSS-Yunzai  |       '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)',
0|TRSS-Yunzai  |     echo: '01J87P1MPMFP04ENZ3HTRE85SA',
0|TRSS-Yunzai  |     raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 请指定 group_id 或 user_id\\n    at createContext (file:///app/napcat/napcat.mjs:36663:9)\\n    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\\n    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)","wording":"Error: 请指定 group_id 或 user_id\\n    at createContext (file:///app/napcat/napcat.mjs:36663:9)\\n    at SendMsg._handle (file:///app/napcat/napcat.mjs:36688:24)\\n    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36606:34)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)","echo":"01J87P1MPMFP04ENZ3HTRE85SA"}'
0|TRSS-Yunzai  |   }
0|TRSS-Yunzai  | }
```

**Comment by MIUKUKANO** [comment]
大佬，我也遇到了。想问一下解决了吗？我目前是回到旧版napcat，不会出现 。

**Comment by 127Wzc** [comment]
send_msg 缺少类型 私聊识别不了 可以自己加一下。今天升级nc也遇到了。加上message_type ok了
<img width="883" alt="image" src="https://github.com/user-attachments/assets/cb4cac81-ef89-475c-8140-fe255d92652b">
