### ISSUE TITLE
导入抽卡记录失败

### ISSUE THREAD

**Issue by ssxwcz** [TimeRainStarSky/Yunzai#19]
```log
[TRSSYz][22:33:38.100][INFO] [wxid_21idn10ee1t122] 未知消息：{"id":"453cd0b6-cef8-4cb3-a788-ad130ab9f1ed","time":1683729216,"type":"notice","detail_type":"wx.get_private_file","sub_type":"","self":{"platform":"wechat","user_id":"wxid_21idn10ee1t122"},"file_name":"192608688.json","file_length":797298,"md5":"2566b0e049588196d1d64b8c3474d05e","user_id":"wxid_yrvzxjsk","self_id":"wxid_21idn10ee1t122","bot":{"version":{"impl":"ComWechat","version":"v1.0","onebot_version":"12"},"stat":{"start_time":1683727903.4006188},"info":{"user_id":"wxid_21idn10ee1t122","user_name":"xxx","user_displayname":"","wx.sex":"未知","wx.wx_number":"xxxx","wx.avatar":"http://wx.qlogo.cn/mmhead/ver_1/806Sk6I4XXZOYsFoIIUhpCJlZrE2MgPKBTibdIxaAwHjdibDwpicCL0H2Qmw2icsAfzgbtGicaicOjPkGmZpKKF3bvaQNibibGIeJLT217OiaWibKFians/0"},"uin":"wxid_21idn10ee1t122","nickname":"xxx","avatar":"http://wx.qlogo.cn/mmhead/ver_1/806Sk6I4XXZOYsFoIIUhpCJlZrE2MgPKBTibdIxaAwHjdibDwpicCL0H2Qmw2icsAfzgbtGicaicOjPkGmZpKKF3bvaQNibibGIeJLT217OiaWibKFians/0","fl":{},"gl":{}}}
[TRSSYz][22:33:39.584][INFO] [wxid_21idn10ee1t122] 好友消息：[wxid_yrvzxjsk] [文件]
[TRSSYz][22:33:39.592][ERRO] TypeError: Cannot read properties of undefined (reading 'includes')
    at gcLog.accept (file:///C:/Users/Administrator/Apps/Yunzai/plugins/genshin/apps/gcLog.js:70:16)
    at PluginsLoader.deal (file:///C:/Users/Administrator/Apps/Yunzai/lib/plugins/loader.js:250:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
ComWeChat端日志
```log
05-10 22:37:42 [ DEBUG ] wechatbot_client | Com WeChat | 接收到wechat消息 - {"extrainfo":"<msgsource>\n\t<sec_msg_node>\n\t\t<uuid>ed49ca223b8f92a3480f88ebedbc16a6_</uuid>\n\t</sec_msg_node>\n\t<signature>v1_XcaXq8Fe</signature>\n\t<tmp_node>\n\t\t<publisher-id>&lt;![CDATA[]]&gt;</publisher-id>\n\t</tmp_node>\n</msgsource>\n","filepath":"wxid_21idn10ee1t122\\FileStorage\\MsgAttach\\e20b0fb6400b94c9b247bb538791d26f\\File\\2023-05\\192608688(1).json","isSendMsg":0,"message":"<?xml version=\"1.0\"?>\n<msg>\n\t<appmsg appid=\"wx6618f1cfc6c132f8\" sdkver=\"0\">\n\t\t<title>192608688.json</title>\n\t\t<des />\n\t\t<action>view</action>\n\t\t<type>6</type>\n\t\t<showtype>0</showtype>\n\t\t<content />\n\t\t<url />\n\t\t<dataurl />\n\t\t<lowurl />\n\t\t<lowdataurl />\n\t\t<recorditem />\n\t\t<thumburl />\n\t\t<messageaction />\n\t\t<laninfo />\n\t\t<md5>2566b0e049588196d1d64b8c3474d05e</md5>\n\t\t<extinfo />\n\t\t<sourceusername />\n\t\t<sourcedisplayname />\n\t\t<commenturl />\n\t\t<appattach>\n\t\t\t<totallen>797298</totallen>\n\t\t\t<attachid>@cdn_3057020100044b304902010002049ea1a7cd02032f5aa90204919969710204645baa91042431616431393538622d623733662d343136362d393837302d6233396536663063396131640204011800050201000405004c4dfd00_babd1d04407b7a77fb981d3efcedd226_1</attachid>\n\t\t\t<emoticonmd5></emoticonmd5>\n\t\t\t<fileext>json</fileext>\n\t\t\t<fileuploadtoken>v1_0WlzoMTfxOcZGne8TIU7UzkkIrooIdBmw8ix8JYOEy9Bt8+qVZNLMHOoTpiDFLObv2lWl5+h1wUCJzqPa5H3kZ/fFmF8fvD3EEZbfjYUw3dCMFjxQZMsDjCKPu/UncsYeejxSSdPwtUm+DwQU9TvFeH7VgF8MS1JNrgxloSQrLu8QCDM73uIkKeBGfcwT6XmFLe7Zni22PGgrG0h6xnWnz3XgeN+NVGnKIQy</fileuploadtoken>\n\t\t\t<overwrite_newmsgid>194997407035857549</overwrite_newmsgid>\n\t\t\t<filekey>8142dca50f91a2f05ca970e7a29794b3</filekey>\n\t\t\t<cdnattachurl>3057020100044b304902010002049ea1a7cd02032f5aa90204919969710204645baa91042431616431393538622d623733662d343136362d393837302d6233396536663063396131640204011800050201000405004c4dfd00</cdnattachurl>\n\t\t\t<aeskey>babd1d04407b7a77fb981d3efcedd226</aeskey>\n\t\t\t<encryver>1</encryver>\n\t\t</appattach>\n\t\t<weappinfo>\n\t\t\t<pagepath />\n\t\t\t<username />\n\t\t\t<appid />\n\t\t\t<appservicetype>0</appservicetype>\n\t\t</weappinfo>\n\t\t<websearch />\n\t</appmsg>\n\t<fromusername>wxid_yrvzxjsk7pli22</fromusername>\n\t<scene>0</scene>\n\t<appinfo>\n\t\t<version>7</version>\n\t\t<appname>微信电脑版</appname>\n\t</appinfo>\n\t<commenturl />\n</msg>\n","msgid":7443229119368653224,"pid":4336,"self":"wxid_21idn10ee1t122","sender":"wxid_yrvzxjsk7pli22","sign":"1732415bf8a0932c0dceb644df6ae4a8","thumb_path":"","time":"2023-05-10 22:37:41","timestamp":1683729461,"type":49,"wxid":"wxid_yrvzxjsk7pli22"}
```
抽卡记录是标准的UIGF文件，comwechat这边日志是收到了文件的消息

**Comment by TimeRainStarSky** [comment]
文件收发暂未实现，等待后续更新
