### ISSUE TITLE
绑定cookie报错

### ISSUE THREAD

**Issue by ddaodan** [TimeRainStarSky/Yunzai#26]
[TRSSYz][13:09:39.085][MARK] [用户绑定][bingCk][私聊][***] #绑定cookie
[TRSSYz][13:09:39.086][ERRO] [用户绑定][bingCk]
[TRSSYz][13:09:39.086][ERRO] TypeError: mys.setCkData is not a function
    at User.bing (file:///root/BOT/Yunzai/plugins/genshin/model/user.js:84:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async user.bingCk (file:///root/BOT/Yunzai/plugins/genshin/apps/user.js:129:5)
    at async PluginsLoader.deal (file:///root/BOT/Yunzai/lib/plugins/loader.js:291:52)

**Comment by TimeRainStarSky** [comment]
`#全部更新`

**Comment by ddaodan** [comment]
> `#全部更新`

还是不行，貌似是yunzai更新之后出现的问题
