### ISSUE TITLE
使用全部更新后无法正常使用TRSSyunzai

### ISSUE THREAD

**Issue by Rockney99** [TimeRainStarSky/Yunzai#29]
TypeError: MysInfo.getNoteUser is not a function
    at Function.init (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/plugins/runtime.js:61:28)
    at PluginsLoader.deal (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/plugins/loader.js:208:19)
    at messageEvent.execute (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/events/message.js:12:18)
    at Yunzai.<anonymous> (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/listener/loader.js:29:73)
    at Yunzai.emit (node:events:525:35)
    at gocqhttpAdapter.makeMessage (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/adapter/WebSocket/go-cqhttp.js:480:9)
    at gocqhttpAdapter.message (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/adapter/WebSocket/go-cqhttp.js:660:16)
    at WebSocket.<anonymous> (file:///C:/Users/Administrator/Downloads/Genshin-bot/TRSS-Yunzai/Yunzai/lib/adapter/WebSocket/go-cqhttp.js:687:37)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\Administrator\Downloads\Genshin-bot\TRSS-Yunzai\Yunzai\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:1184:20)

**Comment by TimeRainStarSky** [comment]
```
git reset --hard
git pull --rebase
rm -rf plugins/genshin
git clone --depth 1 https://gitee.com/TimeRainStarSky/Yunzai-genshin plugins/genshin
```
