### ISSUE TITLE
无法连接到Discord

### ISSUE THREAD

**Issue by kae-mihara** [TimeRainStarSky/Yunzai#31]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/7193933/a82f5b10-23ad-44b7-9ae9-a518dc1acf4f)
尝试设置token无响应。
因为服务器在国外，没有配置反代和代理。

**Comment by TheTychoStar** [comment]
> ![image](https://user-images.githubusercontent.com/7193933/249338085-a82f5b10-23ad-44b7-9ae9-a518dc1acf4f.png) 尝试设置token无响应。 因为服务器在国外，没有配置反代和代理。

解决了吗兄弟？我也想设置discord但是不成功。错误日志如下：
`[TRSSYz][01:29:20.405][DEBU] 加载适配器：DiscordBot(Discord)
[TRSSYz][01:29:21.082][ERRO] Error: Disallowed intents specified
    at Shard._onWSClose (/home/ec2-user/trss/node_modules/.pnpm/eris@0.17.2/node_modules/eris/lib/gateway/Shard.js:2568:23)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/home/ec2-user/trss/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:258:10)
    at TLSSocket.socketOnClose (/home/ec2-user/trss/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:1264:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:301:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 4014`

**Comment by TheTychoStar** [comment]
经高人指点搞明白了，是DC的BOT选项里这三个要打开才行，打开以后就可以正常连接BOT了。
![image](https://github.com/TimeRainStarSky/Yunzai/assets/75252778/60d08312-8656-4c27-86ad-aa51b3bf737d)

**Comment by TimeRainStarSky** [comment]
无响应就是连不上Discord服务器，自己检查
