### ISSUE TITLE
[ERROR]: Report SQLITE_ERROR: no such column: games

### ISSUE THREAD

**Issue by wiketool** [TimeRainStarSky/Yunzai#43]
After restart the container, It report Error: SQLITE_ERROR: no such column: games
```
trss-yunzai  |  [TRSSYz][11:50:41.494][ERRO]  Error
trss-yunzai  |     at Database.<anonymous> (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
trss-yunzai  |     at /app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
trss-yunzai  |     at new Promise (<anonymous>)
trss-yunzai  |     at Query.run (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
trss-yunzai  |     at /app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/sequelize.js:315:28
trss-yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
trss-yunzai  |     at async SQLiteQueryInterface.select (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
trss-yunzai  |     at async UserDB.findAll (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1140:21)
trss-yunzai  |     at async UserDB.findOne (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1240:12)
trss-yunzai  |     at async UserDB.findByPk (/app/TRSS-Yunzai/node_modules/.pnpm/sequelize@6.32.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1221:12) {
trss-yunzai  |   name: 'SequelizeDatabaseError',
trss-yunzai  |   parent: [Error: SQLITE_ERROR: no such column: games] {
trss-yunzai  |     errno: 1,
trss-yunzai  |     code: 'SQLITE_ERROR',
trss-yunzai  |     sql: "SELECT `id`, `type`, `name`, `face`, `ltuids`, `games`, `data`, `createdAt`, `updatedAt` FROM `Users` AS `UserDB` WHERE `UserDB`.`id` = '2523677307';"
trss-yunzai  |   },
trss-yunzai  |   original: [Error: SQLITE_ERROR: no such column: games] {
trss-yunzai  |     errno: 1,
trss-yunzai  |     code: 'SQLITE_ERROR',
trss-yunzai  |     sql: "SELECT `id`, `type`, `name`, `face`, `ltuids`, `games`, `data`, `createdAt`, `updatedAt` FROM `Users` AS `UserDB` WHERE `UserDB`.`id` = '2523677307';"
trss-yunzai  |   },
trss-yunzai  |   sql: "SELECT `id`, `type`, `name`, `face`, `ltuids`, `games`, `data`, `createdAt`, `updatedAt` FROM `Users` AS `UserDB` WHERE `UserDB`.`id` = '2523677307';",
trss-yunzai  |   parameters: {}
trss-yunzai  | }
```

**Comment by TimeRainStarSky** [comment]
数据库问题，找上游 Miao-Yunzai 反馈，删除 data/db 临时解决
