### ISSUE TITLE
更新后闲心插件出现错误undefined (reading'gl')

### ISSUE THREAD

**Issue by ayakasuki** [TimeRainStarSky/Yunzai#52]
[TRSSYz][22:35:12.625][ERRO] TypeError: Cannot read properties of undefined (reading 'gl')
    at Yunzai.getGroupMap (file:///data1/Yunzai-Bot/Yunzai-TRSS/lib/bot.js:121:42)
    at get gl [as gl] (file:///data1/Yunzai-Bot/Yunzai-TRSS/lib/bot.js:125:26)
    at new forward (file:///data1/Yunzai-Bot/Yunzai-TRSS/plugins/TRSS-Xianxin-Plugin/apps/forward.js:52:34)
    at file:///data1/Yunzai-Bot/Yunzai-TRSS/lib/plugins/loader.js:184:15
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///data1/Yunzai-Bot/Yunzai-TRSS/lib/plugins/loader.js:183:19)

**Comment by ayakasuki** [comment]
自己git pull出现问题 已自行解决

**Comment by TimeRainStarSky** [comment]
找插件作者
