### ISSUE TITLE
使用#兑换码报错

### ISSUE THREAD

**Issue by vraypkhm** [TimeRainStarSky/Yunzai#60]
at async PluginsLoader.deal (file:///usr/local/Miao-Yunzai/lib/plugins/loader.js:291:54)
    at async exchange.getCode (file:///usr/local/Miao-Yunzai/plugins/genshin/apps/exchange.js:30:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runMicrotasks (<anonymous>)
    at exchange.getActId (file:///usr/local/Miao-Yunzai/plugins/genshin/apps/exchange.js:111:27)
[00:19:23.331][ERRO] TypeError: Cannot read properties of undefined (reading 'post')
[00:19:23.330][ERRO] [兑换码][getCode]
[00:19:22.861][MARK] [兑换码][getCode]

求解

**Comment by TimeRainStarSky** [comment]
https://github.com/yoimiya-kokomi/Miao-Yunzai/issues/new
